POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username" : "Eliza",
    "email": "elii56zghgha07@gmail.com",
    "password": "eliza122234"
}
###

POST http://localhost:3000/api/users/delete
Content-Type: application/json

{
    "body" : "recXwzwdgJHo1xnES",
}
###
